[package]
name = "axdtb"
version = "0.1.0"
edition = "2021"
authors = ["Zhetan Liu"]
description = "ArceOS dtb parser"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"

[features]

[dependencies]
dtb = "0.2.0"
log = "0.4"